/**
 * A-1APSVC Pre-loaded Customer Data
 * Imported from user's Excel spreadsheet with proper field names
 */

const PRELOADED_CUSTOMERS = [
    {
        id: 'cust_001',
        firstName: 'Frank',
        lastName: 'Reed',
        email: 'frankpr1980@gmail.com',
        mobilePhone: '(917) 000-0000',
        homePhone: '',
        workPhone: '',
        address: '',
        company: '',
        tags: [],
        notes: '',
        dateAdded: '2024-01-15T10:30:00Z'
    },
    {
        id: 'cust_002',
        firstName: 'Buddy',
        lastName: 'Lane',
        email: '',
        mobilePhone: '(215) 000-0000',
        homePhone: '',
        workPhone: '',
        address: '',
        company: '',
        tags: [],
        notes: '',
        dateAdded: '2024-01-16T09:15:00Z'
    },
    {
        id: 'cust_003',
        firstName: 'Poulins',
        lastName: 'Syriac',
        email: 'poulinssyriac@yahoo.com',
        mobilePhone: '(204) 000-0000',
        homePhone: '',
        workPhone: '',
        address: '',
        company: '',
        tags: [],
        notes: '',
        dateAdded: '2024-01-17T14:20:00Z'
    },
    {
        id: 'cust_004',
        firstName: 'Ruth',
        lastName: 'Young',
        email: 'rayoung258@yahoo.com',
        mobilePhone: '(972) 000-0000',
        homePhone: '',
        workPhone: '',
        address: '',
        company: '',
        tags: ['Snaked an'],
        notes: '',
        dateAdded: '2024-01-18T11:45:00Z'
    },
    {
        id: 'cust_005',
        firstName: 'Pierce',
        lastName: 'Fonville',
        email: 'pierce@rentavations.com',
        mobilePhone: '(817) 000-0000',
        homePhone: '',
        workPhone: '',
        address: '',
        company: 'Rentavations',
        tags: ['Calmont house', 'The'],
        notes: '',
        dateAdded: '2024-01-19T16:30:00Z'
    },
    {
        id: 'cust_006',
        firstName: 'Cathie',
        lastName: 'Lanier',
        email: 'cathie1.la@gmail.com',
        mobilePhone: '(214) 000-0000',
        homePhone: '',
        workPhone: '',
        address: '',
        company: '',
        tags: [],
        notes: '',
        dateAdded: '2024-01-20T08:00:00Z'
    },
    {
        id: 'cust_007',
        firstName: 'Jen',
        lastName: 'Gray',
        email: 'jenngray3904@yahoo.com',
        mobilePhone: '(601) 000-0000',
        homePhone: '',
        workPhone: '',
        address: '',
        company: '',
        tags: [],
        notes: '',
        dateAdded: '2024-01-21T13:15:00Z'
    },
    {
        id: 'cust_008',
        firstName: 'Linda',
        lastName: 'Woody',
        email: 'twoody1231@gmail.com',
        mobilePhone: '(215) 000-0000',
        homePhone: '',
        workPhone: '',
        address: '',
        company: '',
        tags: [],
        notes: '',
        dateAdded: '2024-01-22T10:45:00Z'
    },
    {
        id: 'cust_009',
        firstName: 'Lori',
        lastName: 'Kern',
        email: 'lori.kern@gte.net',
        mobilePhone: '(214) 000-0000',
        homePhone: '',
        workPhone: '',
        address: '',
        company: '',
        tags: [],
        notes: '',
        dateAdded: '2024-01-23T15:20:00Z'
    },
    {
        id: 'cust_010',
        firstName: 'Cristi',
        lastName: 'Day',
        email: 'cristiday@sbcglobal.net',
        mobilePhone: '(807) 000-0000',
        homePhone: '',
        workPhone: '',
        address: '',
        company: '',
        tags: [],
        notes: '',
        dateAdded: '2024-01-24T09:30:00Z'
    },
    {
        id: 'cust_011',
        firstName: 'Jessie',
        lastName: 'Hernandez',
        email: 'jessie.hernandez@protonmail.com',
        mobilePhone: '(306) 000-0000',
        homePhone: '',
        workPhone: '',
        address: '',
        company: '',
        tags: [],
        notes: '',
        dateAdded: '2024-01-25T12:00:00Z'
    },
    {
        id: 'cust_012',
        firstName: 'Brian',
        lastName: 'Johnson',
        email: '',
        mobilePhone: '(215) 000-0000',
        homePhone: '',
        workPhone: '',
        address: '',
        company: '',
        tags: [],
        notes: '',
        dateAdded: '2024-01-26T14:15:00Z'
    },
    {
        id: 'cust_013',
        firstName: 'David',
        lastName: 'Gosnell',
        email: 'david.gosnell@verizon.net',
        mobilePhone: '(470) 000-0000',
        homePhone: '',
        workPhone: '',
        address: '',
        company: '',
        tags: [],
        notes: '',
        dateAdded: '2024-01-27T11:30:00Z'
    },
    {
        id: 'cust_014',
        firstName: 'Matt',
        lastName: '',
        email: '',
        mobilePhone: '(973) 000-0000',
        homePhone: '',
        workPhone: '',
        address: '',
        company: '',
        tags: [],
        notes: '',
        dateAdded: '2024-01-28T16:45:00Z'
    },
    {
        id: 'cust_015',
        firstName: 'Donetta',
        lastName: 'Coleman',
        email: 'coleman5137@gmail.com',
        mobilePhone: '(973) 000-0000',
        homePhone: '',
        workPhone: '',
        address: '',
        company: '',
        tags: [],
        notes: '',
        dateAdded: '2024-01-29T08:20:00Z'
    },
    {
        id: 'cust_016',
        firstName: 'Borja',
        lastName: 'Roig',
        email: 'borjars@gmail.com',
        mobilePhone: '(789) 000-0000',
        homePhone: '',
        workPhone: '',
        address: '',
        company: '',
        tags: [],
        notes: '',
        dateAdded: '2024-01-30T13:10:00Z'
    },
    {
        id: 'cust_017',
        firstName: 'Henry',
        lastName: 'Hernane',
        email: 'hjhernane@yahoo.com',
        mobilePhone: '(951) 000-0000',
        homePhone: '',
        workPhone: '',
        address: '',
        company: '',
        tags: [],
        notes: '',
        dateAdded: '2024-01-31T10:00:00Z'
    },
    {
        id: 'cust_018',
        firstName: 'Hafeez',
        lastName: 'Rahman',
        email: 'hafeez.rahman@gmail.com',
        mobilePhone: '(519) 000-0000',
        homePhone: '',
        workPhone: '',
        address: '',
        company: '',
        tags: [],
        notes: '',
        dateAdded: '2024-02-01T15:25:00Z'
    },
    {
        id: 'cust_019',
        firstName: 'Rita',
        lastName: 'Randle',
        email: 'randle614@gmail.com',
        mobilePhone: '(215) 000-0000',
        homePhone: '',
        workPhone: '',
        address: '',
        company: '',
        tags: [],
        notes: '',
        dateAdded: '2024-02-02T09:40:00Z'
    },
    {
        id: 'cust_020',
        firstName: 'Efrom',
        lastName: 'Moore',
        email: 'efrommoore@comcast.net',
        mobilePhone: '(470) 000-0000',
        homePhone: '',
        workPhone: '',
        address: '',
        company: '',
        tags: [],
        notes: '',
        dateAdded: '2024-02-03T12:55:00Z'
    },
    {
        id: 'cust_021',
        firstName: 'Tina',
        lastName: 'Zhu',
        email: 'tinazhu2007@gmail.com',
        mobilePhone: '',
        homePhone: '',
        workPhone: '',
        address: '',
        company: '',
        tags: [],
        notes: '',
        dateAdded: '2024-02-04T14:30:00Z'
    },
    {
        id: 'cust_022',
        firstName: 'Lulu',
        lastName: '',
        email: '',
        mobilePhone: '(240) 000-0000',
        homePhone: '',
        workPhone: '',
        address: '',
        company: '',
        tags: [],
        notes: '',
        dateAdded: '2024-02-05T11:15:00Z'
    },
    {
        id: 'cust_023',
        firstName: 'Brian',
        lastName: 'Cumberledge',
        email: 'bcumberledge@gmail.com',
        mobilePhone: '(215) 000-0000',
        homePhone: '',
        workPhone: '',
        address: '',
        company: '',
        tags: [],
        notes: '',
        dateAdded: '2024-02-06T16:00:00Z'
    },
    {
        id: 'cust_024',
        firstName: 'Jitcho',
        lastName: '',
        email: 'cdjitcho@gmail.com',
        mobilePhone: '(973) 000-0000',
        homePhone: '',
        workPhone: '',
        address: '',
        company: '',
        tags: [],
        notes: '',
        dateAdded: '2024-02-07T08:45:00Z'
    },
    {
        id: 'cust_025',
        firstName: 'Marie',
        lastName: 'Sandora',
        email: 'smithma1201@gmail.com',
        mobilePhone: '(909) 000-0000',
        homePhone: '',
        workPhone: '',
        address: '',
        company: '',
        tags: [],
        notes: '',
        dateAdded: '2024-02-08T13:20:00Z'
    },
    {
        id: 'cust_026',
        firstName: 'Kathy',
        lastName: 'Sechrist',
        email: '',
        mobilePhone: '(973) 000-0000',
        homePhone: '',
        workPhone: '',
        address: '',
        company: '',
        tags: ['Generator'],
        notes: '',
        dateAdded: '2024-02-09T10:35:00Z'
    },
    {
        id: 'cust_027',
        firstName: 'Binh',
        lastName: 'Le',
        email: 'binhle58@gmail.com',
        mobilePhone: '(817) 000-0000',
        homePhone: '',
        workPhone: '',
        address: '',
        company: '',
        tags: [],
        notes: '',
        dateAdded: '2024-02-10T15:50:00Z'
    },
    {
        id: 'cust_028',
        firstName: 'Stella',
        lastName: 'Cobb',
        email: 'stella.pharivn@gmail.com',
        mobilePhone: '(469) 000-0000',
        homePhone: '',
        workPhone: '',
        address: '',
        company: '',
        tags: [],
        notes: '',
        dateAdded: '2024-02-11T09:25:00Z'
    },
    {
        id: 'cust_029',
        firstName: 'Welbin',
        lastName: 'Yang',
        email: 'ritcare@yahoo.com',
        mobilePhone: '(147) 000-0000',
        homePhone: '',
        workPhone: '',
        address: '',
        company: '',
        tags: [],
        notes: '',
        dateAdded: '2024-02-12T12:40:00Z'
    },
    {
        id: 'cust_030',
        firstName: 'Bill',
        lastName: 'Karraker',
        email: 'karraker@gmail.com',
        mobilePhone: '(972) 000-0000',
        homePhone: '',
        workPhone: '',
        address: '',
        company: '',
        tags: [],
        notes: '',
        dateAdded: '2024-02-13T14:15:00Z'
    },
    {
        id: 'cust_031',
        firstName: 'Abhijit',
        lastName: 'Godbole',
        email: 'godbole.abhijit@gmail.com',
        mobilePhone: '(514) 000-0000',
        homePhone: '',
        workPhone: '',
        address: '',
        company: '',
        tags: [],
        notes: '',
        dateAdded: '2024-02-14T11:30:00Z'
    },
    {
        id: 'cust_032',
        firstName: 'Sissy',
        lastName: 'Huang',
        email: 'sissycynthia@gmail.com',
        mobilePhone: '(941) 000-0000',
        homePhone: '',
        workPhone: '',
        address: '',
        company: '',
        tags: [],
        notes: '',
        dateAdded: '2024-02-15T16:45:00Z'
    },
    {
        id: 'cust_033',
        firstName: 'Rey',
        lastName: 'Nungaray',
        email: 'thenungaraygroup@gmail.com',
        mobilePhone: '(215) 000-0000',
        homePhone: '',
        workPhone: '',
        address: '',
        company: '',
        tags: [],
        notes: '',
        dateAdded: '2024-02-16T08:20:00Z'
    },
    {
        id: 'cust_034',
        firstName: 'Ozzy',
        lastName: 'Polanco',
        email: 'ozziepolanco@gmail.com',
        mobilePhone: '(469) 000-0000',
        homePhone: '',
        workPhone: '',
        address: '',
        company: '',
        tags: [],
        notes: '',
        dateAdded: '2024-02-17T13:35:00Z'
    },
    {
        id: 'cust_035',
        firstName: 'Reyn',
        lastName: 'King',
        email: 'reyn@northmgmt.net',
        mobilePhone: '(325) 000-0000',
        homePhone: '',
        workPhone: '',
        address: '',
        company: '',
        tags: [],
        notes: '',
        dateAdded: '2024-02-18T10:50:00Z'
    },
    {
        id: 'cust_036',
        firstName: 'Mary',
        lastName: 'Cadigan',
        email: 'marylouise@ebby.com',
        mobilePhone: '(214) 000-0000',
        homePhone: '',
        workPhone: '',
        address: '',
        company: '',
        tags: [],
        notes: '',
        dateAdded: '2024-02-19T15:05:00Z'
    },
    {
        id: 'cust_037',
        firstName: 'Brian',
        lastName: 'Collins',
        email: 'bmc1280@gmail.com',
        mobilePhone: '(469) 000-0000',
        homePhone: '',
        workPhone: '',
        address: '',
        company: '',
        tags: [],
        notes: '',
        dateAdded: '2024-02-20T09:20:00Z'
    },
    {
        id: 'cust_038',
        firstName: 'CV',
        lastName: 'Thrivikram',
        email: 'devenkh2@gmail.com',
        mobilePhone: '(973) 000-0000',
        homePhone: '',
        workPhone: '',
        address: '',
        company: '',
        tags: [],
        notes: '',
        dateAdded: '2024-02-21T12:35:00Z'
    },
    {
        id: 'cust_039',
        firstName: 'Susan',
        lastName: 'Yeh',
        email: '54305y@gmail.com',
        mobilePhone: '(210) 000-0000',
        homePhone: '',
        workPhone: '',
        address: '',
        company: '',
        tags: [],
        notes: '',
        dateAdded: '2024-02-22T14:50:00Z'
    },
    {
        id: 'cust_040',
        firstName: 'Scott',
        lastName: 'Christian',
        email: 'scott.christian91@gmail.com',
        mobilePhone: '(214) 000-0000',
        homePhone: '',
        workPhone: '',
        address: '',
        company: '',
        tags: [],
        notes: '',
        dateAdded: '2024-02-23T11:05:00Z'
    },
    {
        id: 'cust_041',
        firstName: 'Audrey',
        lastName: 'Castro',
        email: 'odski@hotmail.com',
        mobilePhone: '(215) 000-0000',
        homePhone: '',
        workPhone: '',
        address: '',
        company: '',
        tags: [],
        notes: '',
        dateAdded: '2024-02-24T16:20:00Z'
    },
    {
        id: 'cust_042',
        firstName: 'Zack',
        lastName: 'Plunkett',
        email: 'zack.plunkett@outlook.com',
        mobilePhone: '(818) 000-0000',
        homePhone: '',
        workPhone: '',
        address: '',
        company: '',
        tags: [],
        notes: '',
        dateAdded: '2024-02-25T08:35:00Z'
    },
    {
        id: 'cust_043',
        firstName: 'Kishore',
        lastName: 'Kasturi',
        email: 'kishorepal@yahoo.com',
        mobilePhone: '(728) 000-0000',
        homePhone: '',
        workPhone: '',
        address: '',
        company: '',
        tags: [],
        notes: '',
        dateAdded: '2024-02-26T13:50:00Z'
    },
    {
        id: 'cust_044',
        firstName: 'Alex',
        lastName: '',
        email: 'info@texasstarbuilder.com',
        mobilePhone: '(771) 000-0000',
        homePhone: '',
        workPhone: '',
        address: '',
        company: 'Texas Star Builder',
        tags: [],
        notes: '',
        dateAdded: '2024-02-27T10:15:00Z'
    },
    {
        id: 'cust_045',
        firstName: 'Ashley',
        lastName: 'Glanton',
        email: '',
        mobilePhone: '(818) 000-0000',
        homePhone: '',
        workPhone: '',
        address: '',
        company: '',
        tags: [],
        notes: '',
        dateAdded: '2024-02-28T15:30:00Z'
    }
];

// Function to initialize customer data if none exists
function initializeCustomerData() {
    const existingCustomers = localStorage.getItem('a1apsvc-customers');
    if (!existingCustomers || JSON.parse(existingCustomers).length === 0) {
        localStorage.setItem('a1apsvc-customers', JSON.stringify(PRELOADED_CUSTOMERS));
        return PRELOADED_CUSTOMERS;
    }
    return JSON.parse(existingCustomers);
}

