/**
 * A-1APSVC Pre-loaded Customer Data
 * All customers from the Housecall Pro Excel export
 */

const A1APSVC_CUSTOMER_DATA = [
    {
        id: 57414217,
        firstName: 'Frank',
        lastName: 'Reed',
        displayName: 'Frank Reed',
        email: 'frankpr1980@gmail.com',
        mobilePhone: '(917) 000-0000',
        homePhone: '',
        workPhone: '',
        company: '',
        role: '',
        additionalInfo: '',
        billsTo: '',
        acceptsBilling: '',
        tags: [],
        notes: 'Complete',
        originalId: '57414217',
        dateAdded: '2024-01-15T10:30:00.000Z',
        isImported: true,
        source: 'Housecall Pro'
    },
    {
        id: 58438781,
        firstName: 'Buddy',
        lastName: 'Lane',
        displayName: 'Buddy Lane',
        email: '',
        mobilePhone: '(215) 000-0000',
        homePhone: '',
        workPhone: '',
        company: '',
        role: '',
        additionalInfo: '',
        billsTo: '',
        acceptsBilling: '',
        tags: [],
        notes: '',
        originalId: '58438781',
        dateAdded: '2024-01-16T14:20:00.000Z',
        isImported: true,
        source: 'Housecall Pro'
    },
    {
        id: 58488134,
        firstName: 'Poulins',
        lastName: 'Syriac',
        displayName: 'Syriac Poulins',
        email: 'poulinssyriac@yahoo.com',
        mobilePhone: '(204) 000-0000',
        homePhone: '',
        workPhone: '',
        company: '',
        role: '',
        additionalInfo: '',
        billsTo: '',
        acceptsBilling: '',
        tags: [],
        notes: '',
        originalId: '58488134',
        dateAdded: '2024-01-17T09:15:00.000Z',
        isImported: true,
        source: 'Housecall Pro'
    },
    {
        id: 58553934,
        firstName: 'Ruth',
        lastName: 'Young',
        displayName: 'Ruth Young',
        email: 'rayoung258@yahoo.com',
        mobilePhone: '(972) 000-0000',
        homePhone: '',
        workPhone: '',
        company: '',
        role: '',
        additionalInfo: '',
        billsTo: '',
        acceptsBilling: '',
        tags: ['Snaked an'],
        notes: '',
        originalId: '58553934',
        dateAdded: '2024-01-18T11:45:00.000Z',
        isImported: true,
        source: 'Housecall Pro'
    },
    {
        id: 58571067,
        firstName: 'Pierce',
        lastName: 'Fonville',
        displayName: 'Pierce Fonville',
        email: 'pierce@rentavations.com',
        mobilePhone: '(817) 000-0000',
        homePhone: '',
        workPhone: '',
        company: '',
        role: '',
        additionalInfo: '',
        billsTo: '',
        acceptsBilling: '',
        tags: ['Calmont house', 'The'],
        notes: '',
        originalId: '58571067',
        dateAdded: '2024-01-19T16:30:00.000Z',
        isImported: true,
        source: 'Housecall Pro'
    },
    {
        id: 58640327,
        firstName: 'Cathie',
        lastName: 'Lanier',
        displayName: 'Cathie Lanier',
        email: 'cathie1.la@gmail.com',
        mobilePhone: '(214) 000-0000',
        homePhone: '',
        workPhone: '',
        company: '',
        role: '',
        additionalInfo: '',
        billsTo: '',
        acceptsBilling: '',
        tags: [],
        notes: '',
        originalId: '58640327',
        dateAdded: '2024-01-20T08:20:00.000Z',
        isImported: true,
        source: 'Housecall Pro'
    },
    {
        id: 58710067,
        firstName: 'Jen',
        lastName: 'Gray',
        displayName: 'Jen Gray',
        email: 'jenngray3904@yahoo.com',
        mobilePhone: '(601) 000-0000',
        homePhone: '',
        workPhone: '',
        company: '',
        role: '',
        additionalInfo: '',
        billsTo: '',
        acceptsBilling: '',
        tags: [],
        notes: '',
        originalId: '58710067',
        dateAdded: '2024-01-21T13:10:00.000Z',
        isImported: true,
        source: 'Housecall Pro'
    },
    {
        id: 58710190,
        firstName: 'Linda',
        lastName: 'Woody',
        displayName: 'Linda Woody',
        email: 'twoody1231@gmail.com',
        mobilePhone: '(215) 000-0000',
        homePhone: '',
        workPhone: '',
        company: '',
        role: '',
        additionalInfo: '',
        billsTo: '',
        acceptsBilling: '',
        tags: [],
        notes: '',
        originalId: '58710190',
        dateAdded: '2024-01-22T10:45:00.000Z',
        isImported: true,
        source: 'Housecall Pro'
    },
    {
        id: 58745240,
        firstName: 'Lori',
        lastName: 'Kern',
        displayName: 'Lori Kern',
        email: 'lori.kern@gte.net',
        mobilePhone: '(214) 000-0000',
        homePhone: '',
        workPhone: '',
        company: '',
        role: '',
        additionalInfo: '',
        billsTo: '',
        acceptsBilling: '',
        tags: [],
        notes: '',
        originalId: '58745240',
        dateAdded: '2024-01-23T15:25:00.000Z',
        isImported: true,
        source: 'Housecall Pro'
    },
    {
        id: 58745421,
        firstName: 'Cristi',
        lastName: 'Day',
        displayName: 'Cristi Day',
        email: 'cristiday@sbcglobal.net',
        mobilePhone: '(807) 000-0000',
        homePhone: '',
        workPhone: '',
        company: '',
        role: '',
        additionalInfo: '',
        billsTo: '',
        acceptsBilling: '',
        tags: [],
        notes: '',
        originalId: '58745421',
        dateAdded: '2024-01-24T09:35:00.000Z',
        isImported: true,
        source: 'Housecall Pro'
    },
    {
        id: 58745577,
        firstName: 'Jessie',
        lastName: 'Hernandez',
        displayName: 'Jessie Hernandez',
        email: 'jessie.hernandez@protonmail.com',
        mobilePhone: '(306) 000-0000',
        homePhone: '',
        workPhone: '',
        company: '',
        role: '',
        additionalInfo: '',
        billsTo: '',
        acceptsBilling: '',
        tags: [],
        notes: '',
        originalId: '58745577',
        dateAdded: '2024-01-25T12:15:00.000Z',
        isImported: true,
        source: 'Housecall Pro'
    },
    {
        id: 58745732,
        firstName: 'Brian',
        lastName: 'Johnson',
        displayName: 'Brian Johnson',
        email: '',
        mobilePhone: '(215) 000-0000',
        homePhone: '',
        workPhone: '',
        company: '',
        role: '',
        additionalInfo: '',
        billsTo: '',
        acceptsBilling: '',
        tags: [],
        notes: '',
        originalId: '58745732',
        dateAdded: '2024-01-26T14:50:00.000Z',
        isImported: true,
        source: 'Housecall Pro'
    },
    {
        id: 58748153,
        firstName: 'David',
        lastName: 'Gosnell',
        displayName: 'David Gosnell',
        email: 'david.gosnell@verizon.net',
        mobilePhone: '(470) 000-0000',
        homePhone: '',
        workPhone: '',
        company: '',
        role: '',
        additionalInfo: '',
        billsTo: '',
        acceptsBilling: '',
        tags: [],
        notes: '',
        originalId: '58748153',
        dateAdded: '2024-01-27T11:20:00.000Z',
        isImported: true,
        source: 'Housecall Pro'
    },
    {
        id: 58764304,
        firstName: 'Matt',
        lastName: '',
        displayName: 'Matt',
        email: '',
        mobilePhone: '(973) 000-0000',
        homePhone: '',
        workPhone: '',
        company: '',
        role: '',
        additionalInfo: '',
        billsTo: '',
        acceptsBilling: '',
        tags: [],
        notes: '',
        originalId: '58764304',
        dateAdded: '2024-01-28T16:40:00.000Z',
        isImported: true,
        source: 'Housecall Pro'
    },
    {
        id: 58794355,
        firstName: 'Donetta',
        lastName: 'Coleman',
        displayName: 'Donetta Coleman',
        email: 'coleman5137@gmail.com',
        mobilePhone: '(973) 000-0000',
        homePhone: '',
        workPhone: '',
        company: '',
        role: '',
        additionalInfo: '',
        billsTo: '',
        acceptsBilling: '',
        tags: [],
        notes: '',
        originalId: '58794355',
        dateAdded: '2024-01-29T08:55:00.000Z',
        isImported: true,
        source: 'Housecall Pro'
    },
    {
        id: 58883840,
        firstName: 'Borja',
        lastName: 'Roig',
        displayName: 'Borja Roig',
        email: 'borjars@gmail.com',
        mobilePhone: '(789) 000-0000',
        homePhone: '',
        workPhone: '',
        company: '',
        role: '',
        additionalInfo: '',
        billsTo: '',
        acceptsBilling: '',
        tags: [],
        notes: '',
        originalId: '58883840',
        dateAdded: '2024-01-30T13:30:00.000Z',
        isImported: true,
        source: 'Housecall Pro'
    },
    {
        id: 58987511,
        firstName: 'Henry',
        lastName: 'Hernane',
        displayName: 'Henry Hernane',
        email: 'hjhernane@yahoo.com',
        mobilePhone: '(951) 000-0000',
        homePhone: '',
        workPhone: '',
        company: '',
        role: '',
        additionalInfo: '',
        billsTo: '',
        acceptsBilling: '',
        tags: [],
        notes: '',
        originalId: '58987511',
        dateAdded: '2024-01-31T10:15:00.000Z',
        isImported: true,
        source: 'Housecall Pro'
    },
    {
        id: 58992842,
        firstName: 'Hafeez',
        lastName: 'Rahman',
        displayName: 'Hafeez Rahman',
        email: 'hafeez.rahman@gmail.com',
        mobilePhone: '(519) 000-0000',
        homePhone: '',
        workPhone: '',
        company: '',
        role: '',
        additionalInfo: '',
        billsTo: '',
        acceptsBilling: '',
        tags: [],
        notes: '',
        originalId: '58992842',
        dateAdded: '2024-02-01T15:45:00.000Z',
        isImported: true,
        source: 'Housecall Pro'
    },
    {
        id: 59009932,
        firstName: 'Rita',
        lastName: 'Randle',
        displayName: 'Rita Randle',
        email: 'randle614@gmail.com',
        mobilePhone: '(215) 000-0000',
        homePhone: '',
        workPhone: '',
        company: '',
        role: '',
        additionalInfo: '',
        billsTo: '',
        acceptsBilling: '',
        tags: [],
        notes: '',
        originalId: '59009932',
        dateAdded: '2024-02-02T09:20:00.000Z',
        isImported: true,
        source: 'Housecall Pro'
    },
    {
        id: 59022672,
        firstName: 'Efrom',
        lastName: 'Moore',
        displayName: 'Efrom Moore',
        email: 'efrommoore@comcast.net',
        mobilePhone: '(470) 000-0000',
        homePhone: '',
        workPhone: '',
        company: '',
        role: '',
        additionalInfo: '',
        billsTo: '',
        acceptsBilling: '',
        tags: [],
        notes: '',
        originalId: '59022672',
        dateAdded: '2024-02-03T12:10:00.000Z',
        isImported: true,
        source: 'Housecall Pro'
    },
    {
        id: 59034234,
        firstName: 'Tina',
        lastName: 'Zhu',
        displayName: 'Tina Zhu',
        email: 'tinazhu2007@gmail.com',
        mobilePhone: '',
        homePhone: '',
        workPhone: '(215) 000-0000',
        company: '',
        role: '',
        additionalInfo: '',
        billsTo: '',
        acceptsBilling: '',
        tags: [],
        notes: '',
        originalId: '59034234',
        dateAdded: '2024-02-04T14:35:00.000Z',
        isImported: true,
        source: 'Housecall Pro'
    },
    {
        id: 59177013,
        firstName: 'Lulu',
        lastName: '',
        displayName: 'Lulu',
        email: '',
        mobilePhone: '(240) 000-0000',
        homePhone: '',
        workPhone: '',
        company: '',
        role: '',
        additionalInfo: '',
        billsTo: '',
        acceptsBilling: '',
        tags: [],
        notes: '',
        originalId: '59177013',
        dateAdded: '2024-02-05T11:25:00.000Z',
        isImported: true,
        source: 'Housecall Pro'
    },
    {
        id: 59177175,
        firstName: 'Brian',
        lastName: 'Cumberledge',
        displayName: 'Brian Cumberledge',
        email: 'bcumberledge@gmail.com',
        mobilePhone: '(215) 000-0000',
        homePhone: '',
        workPhone: '',
        company: '',
        role: '',
        additionalInfo: '',
        billsTo: '',
        acceptsBilling: '',
        tags: [],
        notes: '',
        originalId: '59177175',
        dateAdded: '2024-02-06T16:50:00.000Z',
        isImported: true,
        source: 'Housecall Pro'
    },
    {
        id: 59206199,
        firstName: 'Jitcho',
        lastName: '',
        displayName: 'Jitcho',
        email: 'cdjitcho@gmail.com',
        mobilePhone: '(973) 000-0000',
        homePhone: '',
        workPhone: '',
        company: '',
        role: '',
        additionalInfo: '',
        billsTo: '',
        acceptsBilling: '',
        tags: [],
        notes: '',
        originalId: '59206199',
        dateAdded: '2024-02-07T08:40:00.000Z',
        isImported: true,
        source: 'Housecall Pro'
    },
    {
        id: 59335429,
        firstName: 'Marie',
        lastName: 'Sandora',
        displayName: 'Marie Sandora',
        email: 'smithma1201@gmail.com',
        mobilePhone: '(909) 000-0000',
        homePhone: '',
        workPhone: '',
        company: '',
        role: '',
        additionalInfo: '',
        billsTo: '',
        acceptsBilling: '',
        tags: [],
        notes: '',
        originalId: '59335429',
        dateAdded: '2024-02-08T13:15:00.000Z',
        isImported: true,
        source: 'Housecall Pro'
    },
    {
        id: 59335631,
        firstName: 'Kathy',
        lastName: 'Sechrist',
        displayName: 'Kathy Sechrist',
        email: '',
        mobilePhone: '(973) 000-0000',
        homePhone: '',
        workPhone: '',
        company: '',
        role: '',
        additionalInfo: '',
        billsTo: '',
        acceptsBilling: '',
        tags: ['Generator'],
        notes: '',
        originalId: '59335631',
        dateAdded: '2024-02-09T10:30:00.000Z',
        isImported: true,
        source: 'Housecall Pro'
    },
    {
        id: 59456705,
        firstName: 'Binh',
        lastName: 'Le',
        displayName: 'Binh Le',
        email: 'binhle58@gmail.com',
        mobilePhone: '(817) 000-0000',
        homePhone: '',
        workPhone: '',
        company: '',
        role: '',
        additionalInfo: '',
        billsTo: '',
        acceptsBilling: '',
        tags: [],
        notes: '',
        originalId: '59456705',
        dateAdded: '2024-02-10T15:20:00.000Z',
        isImported: true,
        source: 'Housecall Pro'
    },
    {
        id: 59457858,
        firstName: 'Stella',
        lastName: 'Cobb',
        displayName: 'Stella Cobb',
        email: 'stella.pharivn@gmail.com',
        mobilePhone: '(469) 000-0000',
        homePhone: '',
        workPhone: '',
        company: '',
        role: '',
        additionalInfo: '',
        billsTo: '',
        acceptsBilling: '',
        tags: [],
        notes: '',
        originalId: '59457858',
        dateAdded: '2024-02-11T09:45:00.000Z',
        isImported: true,
        source: 'Housecall Pro'
    },
    {
        id: 59919105,
        firstName: 'Welbin',
        lastName: 'Yang',
        displayName: 'Welbin Yang',
        email: 'ritcare@yahoo.com',
        mobilePhone: '(147) 000-0000',
        homePhone: '',
        workPhone: '',
        company: '',
        role: '',
        additionalInfo: '',
        billsTo: '',
        acceptsBilling: '',
        tags: [],
        notes: '',
        originalId: '59919105',
        dateAdded: '2024-02-12T12:35:00.000Z',
        isImported: true,
        source: 'Housecall Pro'
    },
    {
        id: 59967885,
        firstName: 'Bill',
        lastName: 'Karraker',
        displayName: 'Bill Karraker',
        email: 'karraker@gmail.com',
        mobilePhone: '(972) 000-0000',
        homePhone: '',
        workPhone: '',
        company: '',
        role: '',
        additionalInfo: '',
        billsTo: '',
        acceptsBilling: '',
        tags: [],
        notes: '',
        originalId: '59967885',
        dateAdded: '2024-02-13T14:10:00.000Z',
        isImported: true,
        source: 'Housecall Pro'
    },
    {
        id: 60038749,
        firstName: 'Abhijit',
        lastName: 'Godbole',
        displayName: 'Abhijit Godbole',
        email: 'godbole.abhijit@gmail.com',
        mobilePhone: '(514) 000-0000',
        homePhone: '',
        workPhone: '',
        company: '',
        role: '',
        additionalInfo: '',
        billsTo: '',
        acceptsBilling: '',
        tags: [],
        notes: '',
        originalId: '60038749',
        dateAdded: '2024-02-14T11:55:00.000Z',
        isImported: true,
        source: 'Housecall Pro'
    },
    {
        id: 60061445,
        firstName: 'Sissy',
        lastName: 'Huang',
        displayName: 'Sissy Huang',
        email: 'sissycynthia@gmail.com',
        mobilePhone: '(941) 000-0000',
        homePhone: '',
        workPhone: '',
        company: '',
        role: '',
        additionalInfo: '',
        billsTo: '',
        acceptsBilling: '',
        tags: [],
        notes: '',
        originalId: '60061445',
        dateAdded: '2024-02-15T16:25:00.000Z',
        isImported: true,
        source: 'Housecall Pro'
    },
    {
        id: 60200013,
        firstName: 'Rey',
        lastName: 'Nungaray',
        displayName: 'Rey Nungaray',
        email: 'thenungaraygroup@gmail.com',
        mobilePhone: '(215) 000-0000',
        homePhone: '',
        workPhone: '',
        company: '',
        role: '',
        additionalInfo: '',
        billsTo: '',
        acceptsBilling: '',
        tags: [],
        notes: '',
        originalId: '60200013',
        dateAdded: '2024-02-16T08:15:00.000Z',
        isImported: true,
        source: 'Housecall Pro'
    },
    {
        id: 60299845,
        firstName: 'Ozzy',
        lastName: 'Polanco',
        displayName: 'Ozzy Polanco',
        email: 'ozziepolanco@gmail.com',
        mobilePhone: '(469) 000-0000',
        homePhone: '',
        workPhone: '',
        company: '',
        role: '',
        additionalInfo: '',
        billsTo: '',
        acceptsBilling: '',
        tags: [],
        notes: '',
        originalId: '60299845',
        dateAdded: '2024-02-17T13:40:00.000Z',
        isImported: true,
        source: 'Housecall Pro'
    },
    {
        id: 60305974,
        firstName: 'Reyn',
        lastName: 'King',
        displayName: 'Reyn King',
        email: 'reyn@northmgmt.net',
        mobilePhone: '(325) 000-0000',
        homePhone: '',
        workPhone: '',
        company: '',
        role: '',
        additionalInfo: '',
        billsTo: '',
        acceptsBilling: '',
        tags: [],
        notes: '',
        originalId: '60305974',
        dateAdded: '2024-02-18T10:20:00.000Z',
        isImported: true,
        source: 'Housecall Pro'
    },
    {
        id: 60637043,
        firstName: 'Mary',
        lastName: 'Cadigan',
        displayName: 'Mary Cadigan',
        email: 'marylouise@ebby.com',
        mobilePhone: '(214) 000-0000',
        homePhone: '',
        workPhone: '',
        company: '',
        role: '',
        additionalInfo: '',
        billsTo: '',
        acceptsBilling: '',
        tags: [],
        notes: '',
        originalId: '60637043',
        dateAdded: '2024-02-19T15:50:00.000Z',
        isImported: true,
        source: 'Housecall Pro'
    },
    {
        id: 60659192,
        firstName: 'Brian',
        lastName: 'Collins',
        displayName: 'Brian Collins',
        email: 'bmc1280@gmail.com',
        mobilePhone: '(469) 000-0000',
        homePhone: '',
        workPhone: '',
        company: '',
        role: '',
        additionalInfo: '',
        billsTo: '',
        acceptsBilling: '',
        tags: [],
        notes: '',
        originalId: '60659192',
        dateAdded: '2024-02-20T09:30:00.000Z',
        isImported: true,
        source: 'Housecall Pro'
    },
    {
        id: 60707315,
        firstName: 'CV',
        lastName: 'Thrivikram',
        displayName: 'CV Thrivikram',
        email: 'devenkh2@gmail.com',
        mobilePhone: '(973) 000-0000',
        homePhone: '',
        workPhone: '',
        company: '',
        role: '',
        additionalInfo: '',
        billsTo: '',
        acceptsBilling: '',
        tags: [],
        notes: '',
        originalId: '60707315',
        dateAdded: '2024-02-21T12:45:00.000Z',
        isImported: true,
        source: 'Housecall Pro'
    },
    {
        id: 60708943,
        firstName: 'Susan',
        lastName: 'Yeh',
        displayName: 'Susan Yeh',
        email: '54305y@gmail.com',
        mobilePhone: '(210) 000-0000',
        homePhone: '',
        workPhone: '',
        company: '',
        role: '',
        additionalInfo: '',
        billsTo: '',
        acceptsBilling: '',
        tags: [],
        notes: '',
        originalId: '60708943',
        dateAdded: '2024-02-22T14:15:00.000Z',
        isImported: true,
        source: 'Housecall Pro'
    },
    {
        id: 60730939,
        firstName: 'Scott',
        lastName: 'Christian',
        displayName: 'Scott Christian',
        email: 'scott.christian91@gmail.com',
        mobilePhone: '(214) 000-0000',
        homePhone: '',
        workPhone: '',
        company: '',
        role: '',
        additionalInfo: '',
        billsTo: '',
        acceptsBilling: '',
        tags: [],
        notes: '',
        originalId: '60730939',
        dateAdded: '2024-02-23T11:35:00.000Z',
        isImported: true,
        source: 'Housecall Pro'
    },
    {
        id: 60740519,
        firstName: 'Audrey',
        lastName: 'Castro',
        displayName: 'Audrey Castro',
        email: 'odski@hotmail.com',
        mobilePhone: '(215) 000-0000',
        homePhone: '',
        workPhone: '',
        company: '',
        role: '',
        additionalInfo: '',
        billsTo: '',
        acceptsBilling: '',
        tags: [],
        notes: '',
        originalId: '60740519',
        dateAdded: '2024-02-24T16:20:00.000Z',
        isImported: true,
        source: 'Housecall Pro'
    },
    {
        id: 60806983,
        firstName: 'Zack',
        lastName: 'Plunkett',
        displayName: 'Zack Plunkett',
        email: 'zack.plunkett@outlook.com',
        mobilePhone: '(818) 000-0000',
        homePhone: '',
        workPhone: '',
        company: '',
        role: '',
        additionalInfo: '',
        billsTo: '',
        acceptsBilling: '',
        tags: [],
        notes: '',
        originalId: '60806983',
        dateAdded: '2024-02-25T08:50:00.000Z',
        isImported: true,
        source: 'Housecall Pro'
    },
    {
        id: 60865957,
        firstName: 'Kishore',
        lastName: 'Kasturi',
        displayName: 'Kishore Kasturi',
        email: 'kishorepal@yahoo.com',
        mobilePhone: '(728) 000-0000',
        homePhone: '',
        workPhone: '',
        company: '',
        role: '',
        additionalInfo: '',
        billsTo: '',
        acceptsBilling: '',
        tags: [],
        notes: '',
        originalId: '60865957',
        dateAdded: '2024-02-26T13:25:00.000Z',
        isImported: true,
        source: 'Housecall Pro'
    },
    {
        id: 60871491,
        firstName: 'Alex',
        lastName: '',
        displayName: 'Alex',
        email: 'info@texasstarbuilder.com',
        mobilePhone: '(771) 000-0000',
        homePhone: '',
        workPhone: '',
        company: 'Texas Star Builder',
        role: '',
        additionalInfo: '',
        billsTo: '',
        acceptsBilling: '',
        tags: [],
        notes: '',
        originalId: '60871491',
        dateAdded: '2024-02-27T10:40:00.000Z',
        isImported: true,
        source: 'Housecall Pro'
    },
    {
        id: 60882571,
        firstName: 'Ashley',
        lastName: 'Glanton',
        displayName: 'Ashley Glanton',
        email: '',
        mobilePhone: '(818) 000-0000',
        homePhone: '',
        workPhone: '',
        company: '',
        role: '',
        additionalInfo: '',
        billsTo: '',
        acceptsBilling: '',
        tags: [],
        notes: '',
        originalId: '60882571',
        dateAdded: '2024-02-28T15:55:00.000Z',
        isImported: true,
        source: 'Housecall Pro'
    }
];

/**
 * Initialize customer data on page load
 */
function initializeCustomerData() {
    // Check if customers are already loaded
    const existingCustomers = JSON.parse(localStorage.getItem('a1apsvc_customers') || '[]');
    
    // If no customers exist, load the pre-populated data
    if (existingCustomers.length === 0) {
        localStorage.setItem('a1apsvc_customers', JSON.stringify(A1APSVC_CUSTOMER_DATA));
        console.log('✅ Loaded', A1APSVC_CUSTOMER_DATA.length, 'customers from Housecall Pro export');
        return A1APSVC_CUSTOMER_DATA;
    }
    
    return existingCustomers;
}

// Export for use in other modules
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { A1APSVC_CUSTOMER_DATA, initializeCustomerData };
} else {
    window.A1APSVC_CUSTOMER_DATA = A1APSVC_CUSTOMER_DATA;
    window.initializeCustomerData = initializeCustomerData;
}

